# Generated by Django 5.2.6 on 2025-10-06 09:37

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(default='Default', max_length=100)),
                ('vcloud_url', models.URLField()),
                ('vcloud_user', models.CharField(max_length=200)),
                ('vcloud_password', models.CharField(max_length=200)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Cloud Sync Config',
                'verbose_name_plural': 'Cloud Sync Configs',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
