# Generated by Django 5.2.6 on 2025-10-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cloudsync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsyncconfig',
            name='next_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
