# Generated by Django 5.2.6 on 2025-10-06 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('netbox_cloudsync', '0002_cloudsyncconfig_next_sync'),
        ('tenancy', '0020_remove_contactgroupmembership'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsyncconfig',
            name='netbox_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualization.cluster'),
        ),
        migrations.AddField(
            model_name='cloudsyncconfig',
            name='netbox_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.platform'),
        ),
        migrations.AddField(
            model_name='cloudsyncconfig',
            name='netbox_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.devicerole'),
        ),
        migrations.AddField(
            model_name='cloudsyncconfig',
            name='netbox_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.site'),
        ),
        migrations.AddField(
            model_name='cloudsyncconfig',
            name='netbox_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='cloudsyncconfig',
            name='sync_poweroff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cloudsyncconfig',
            name='sync_templates',
            field=models.BooleanField(default=False),
        ),
    ]
